development:
  adapter: postgresql
  encoding: utf8
  database: mission_fitness_development
  pool: 5


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: mission_fitness_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: mission_fitness_app
  pool: 5
